name: viral 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - numpy=1.24.3
  - opencv=4.8.0
  - ffmpeg=6.0
  - pip=23.1.2
  - pip:
      - --find-links https://download.pytorch.org/whl/cu121/torch_stable.html
      - torch==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - torchaudio==2.1.2+cu121
      - yt-dlp==2023.12.30
      - openai-whisper==20231117
      - transformers==4.36.2
      - accelerate==0.25.0
      - bitsandbytes==0.41.3
      - datasets==2.16.1
      - optimum==1.16.2
      - sentence-transformers==2.2.2
      - ultralytics==8.0.232
      - pillow==10.1.0
      - matplotlib==3.8.2
      - seaborn==0.13.0
      - pandas==2.1.4
      - scikit-learn==1.3.2
      - moviepy==1.0.3
      - librosa==0.10.1
      - soundfile==0.12.1
      - requests==2.31.0
      - beautifulsoup4==4.12.2
      - lxml==4.9.3
      - pydantic==2.5.2
      - pydantic-settings
      - typer==0.9.0
      - rich==13.7.0
      - tqdm==4.66.1
      - joblib==1.3.2
      - huggingface-hub==0.19.4
      - safetensors==0.4.1
      - tokenizers==0.15.0
      - diffusers==0.25.0
      - open-clip-torch
      - controlnet-aux
      - face-recognition==1.3.0
      # - xformers  # Skip for now due to CUTLASS submodule issues
      - invisible-watermark
      # - clip-by-openai==1.1  # Requires torch<1.7.2